# ---
#   apiVersion: v1
#   kind: PersistentVolumeClaim
#   metadata:
#     name: mongodb-pvc
#     namespace: cloudacademy
#     labels:
#       app: mongo-db
#   spec:
#     accessModes:
#       - ReadWriteOnce
#     resources:
#       requests:
#         storage: 1Gi
#     storageClassName: gp2
# ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: cloudacademy
spec:
  serviceName: mongo-db
  replicas: 3
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin

            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.25"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"

          ports:
            - containerPort: 27017
              name: mongodb

          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
        namespace: cloudacademy
        annotations:
          volume.beta.kubernetes.io/storage-class: "gp2"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: cloudacademy
  labels:
    app: mongo-db
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-db
