name: CICD

on:
  push:
    paths:
      - "api-go/**"
      - ".github/workflows/go.yaml"
env:
  GITHUB_USER: ishtiaqsamdani007
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: api-go
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: |
        go mod download
        go build -o api
        ls -l
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.GITHUB_USER }}
        password: ${{ secrets.GIT_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./api-go
        push: true
        tags: ghcr.io/${{ env.GITHUB_USER }}/vote-k8s-api:${{ github.sha }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: adding eks-cluster
      env:
        aws_region: ${{ secrets.AWS_REGION }}
        cluster_name: ${{ secrets.CLUSTER_NAME }}
        IMAGE: ghcr.io/${{ env.GITHUB_USER }}/vote-k8s-api:${{ github.sha }}
      run: |
        aws eks --region $aws_region update-kubeconfig --name $cluster_name
        kubectl create namespace cloudacademy --dry-run=client -o yaml | kubectl apply -f -
        kubectl config set-context --current --namespace=cloudacademy
        kubectl set image deployment/api api=$IMAGE
